CREATE OR ALTER PROC FI_SP_ConsBeneficiario
    @ID BIGINT = NULL
AS
BEGIN
    IF (@ID is null OR @ID = 0)
        SELECT NOME, ID, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK)
    ELSE
        SELECT NOME, ID, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID
END

EXEC FI_SP_ConsBeneficiario @ID = 0;